
GET https://localhost/api/eatery/api/food


###


GET http://localhost/eatery/api/_versions


###


GET http://localhost/eatery/api/food/766 HTTP/1.1
content-type: application/json


###

DELETE http://localhost/eatery/api/section/57571 HTTP/1.1
content-type: application/json


###



POST https://localhost/api/food/ HTTP/1.1
content-type: application/json

{
    "name": "Тест 22",
    "section": "674540",
    "price": "1212",
    "images":["https://reservationsteps.ru/files/88/05/8805d5006779ae0999a6bde021020d8e_1050x600.jpg","https://reservationsteps.ru/files/97/d9/97d9a0a8a35332c82009e8b36af6d874_1050x600.jpg"],
    "info": "<ul><li>пицца</li><li>ананасы</li><li>ненависть</li></ul>"
}

###




PUT http://localhost/eatery/api/food/765 HTTP/1.1
content-type: application/json

{
    "name": "Пица с ананасами",
    "section": "57571",
    "price": "300",
    "images":["https://reservationsteps.ru/files/88/05/8805d5006779ae0999a6bde021020d8e_1050x600.jpg","https://reservationsteps.ru/files/97/d9/97d9a0a8a35332c82009e8b36af6d874_1050x600.jpg"],
    "info": "<ul><li>тесто</li><li>ананасы</li><li>мясо</li></ul>"
}

###



POST http://localhost/eatery/api/section/ HTTP/1.1
content-type: application/json

{
    "name": "ВВВ жидкости",
    "order": "2"
}

###

GET http://localhost/eatery/api/section


###

GET http://localhost/eatery/api/section/253979


###

PUT http://localhost/api/order/1 HTTP/1.1
content-type: application/json

{
    "food": [
        {"foodId": "2",
        "price": "50"},
        {"foodId": "3",
        "price": "50"}
    ],
    "any": "aaa"
}

###

POST http://localhost/api/order/ HTTP/1.1

{"name": "Evgeny"}
###

GET http://localhost/api/order/gWpBTkdWQJi HTTP/1.1
















GET http://localhost/eatery/api/food/


###




POST http://localhost/eatery/api/food/ HTTP/1.1
content-type: application/json

{
    "name": "Соус в баночке",
    "section": "57599",
    "price": "50",
    "images":["https://reservationsteps.ru/files/88/05/8805d5006779ae0999a6bde021020d8e_1050x600.jpg","https://reservationsteps.ru/files/97/d9/97d9a0a8a35332c82009e8b36af6d874_1050x600.jpg"],
    "info": "<ul><li>соус</li><li>баночка</li><li>любовь</li></ul>"
}

###




PUT http://localhost/api/food/675538 HTTP/1.1
content-type: application/json

{"id":"","name":"Тест 2","section":"253979","price":"1212","images":["http://localhost/eatery/test_images/1.jpg","http://localhost/eatery/test_images/2.jpg"],"info":"<ul><li>пицца</li><li>ананасы</li><li>ненависть</li></ul>"}

###


POST http://localhost/api/_logins/ HTTP/1.1
content-type: application/json

{"token":"01134A7B7237CF6F980D4B936AE2115D"}
###


POST http://localhost/api/_logins/ HTTP/1.1
content-type: application/json

{"login":"a", "password":"11"}
###